Test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,24 +29,23 @@ jobs:
         run: npx cypress install
       - name: Run Cypress Tests
         run: | 
-          npx cypress run --spec ${{ env.specFile }} 
-        #   > test-results.txt
-        #   echo $? > test-exit-code.txt
-        # continue-on-error: true
-    #   - name: Process Test Results
-    #     id: test-results
-    #     run: |
-    #       if [ -f "test-exit-code.txt" ]; then
-    #         exit_code=$(cat test-exit-code.txt)
-    #         if [ $exit_code -eq 0 ]; then
-    #           echo "pass" > test-status.txt
-    #         else
-    #           echo "fail" > test-status.txt
-    #         fi
-    #       else
-    #         echo "fail" > test-status.txt
-    #       fi
-    #     shell: bash
+          npx cypress run --spec ${{ env.specFile }} > test-results.txt
+          echo $? > test-exit-code.txt
+        continue-on-error: true
+      - name: Process Test Results
+        id: test-results
+        run: |
+          if [ -f "test-exit-code.txt" ]; then
+            exit_code=$(cat test-exit-code.txt)
+            if [ $exit_code -eq 0 ]; then
+              echo "pass" > test-status.txt
+            else
+              echo "fail" > test-status.txt
+            fi
+          else
+            echo "fail" > test-status.txt
+          fi
+        shell: bash
     #   - name: Create Comment
     #     uses: actions/github-script@0.5.0
     #     with:
